version: 2.1

#orbs:
#  slack: circleci/slack@4.12.5

parameters:
  copybara_tag:
    type: string
    default: "v20250818"  

workflows:
  build-workflow:
    jobs:
      - check-connection
      - sync:
          requires:
            - check-connection
jobs:
  check-connection:
    machine: true
    resource_class: gperalta-primehire/gperalta-self-hosted
    environment:
      COPYBARA_TAG: << pipeline.parameters.copybara_tag >>
    steps:
      - run:
          name: Checking conection to Github Cloud 
          command: |
            URL="https://api.github.com/repos/airbnb/viaduct"
            code=$(curl -sS -D /tmp/headers.txt -o /tmp/body.json -w "%{http_code}" \
              -H "Authorization: Bearer ${GH_PAT}" \
              -H "Accept: application/vnd.github+json" "$URL")
            echo "== Response headers =="; cat /tmp/headers.txt
            echo "== Body =="; (jq . /tmp/body.json || cat /tmp/body.json)
            echo "HTTP $code"
            if [ "$code" = "200" ]; then
              echo "✅ Access to to Github Cloud repository"
            fi
            test "${code:0:1}" = "2"

      - run:
          name: Checking connection to GitHub Enterprise
          command: |
            URL="https://git.musta.ch/api/v3/repos/airbnb/treehouse"
            code=$(curl -sS \
              --connect-timeout 5 \
              --max-time 15 \
              --retry 3 \
              --retry-delay 2 \
              --retry-all-errors \
              -D /tmp/headers.txt -o /tmp/body.json -w "%{http_code}" \
              -H "Authorization: Bearer ${GH_PAT_TREEHOUSE}" \
              -H "Accept: application/vnd.github+json" "$URL")
            echo "== Response headers =="; cat /tmp/headers.txt
            echo "== Body =="; (jq . /tmp/body.json || cat /tmp/body.json)
            echo "HTTP $code"
            if [ "$code" = "200" ]; then
              echo "✅ Access to Github Enterprise repository"
            fi
            test "${code:0:1}" = "2"

  sync:
      machine: true
      resource_class: gperalta-primehire/gperalta-self-hosted
      steps:
        - checkout  

        - run:
            name: Install tools (brew)
            command: |
              brew update
              brew install git jq bazelisk openjdk@11
              echo 'export JAVA_HOME=$(/usr/libexec/java_home -v 11)' >> $BASH_ENV
              echo 'export PATH="/usr/local/bin:/opt/homebrew/bin:$PATH"' >> $BASH_ENV
              source $BASH_ENV
              java -version
              bazelisk version

        - run:
            name: Clone Copybara
            command: |
              if [ ! -d copybara ]; then
                git clone https://github.com/google/copybara.git
              fi
              cd copybara
              git fetch --tags --quiet || true
              git checkout "$COPYBARA_TAG" 2>/dev/null || git checkout master

        - run:
            name: Build Copybara
            command: |
              cd copybara
              bazelisk shutdown || true
              bazelisk build //java/com/google/copybara

        - run:
            name: Run Copybara
            command: |
              cd copybara
              ./bazel-bin/java/com/google/copybara/copybara ../.circleci/copybara/copy.bara.sky sync_to_dest --init-history

  #      - slack/notify:
  #          event: pass
  #          template: basic_success_1
 
  #      - slack/notify:
  #          event: fail
  #          template: basic_fail_1

