version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: gperalta-primehire/gperalta-self-hosted
    steps:
      - run: echo "Hi I'm on Runners!"
      - run:
          name: Checking conection to Github Cloud 
          command: |
            curl -f \
              -H "Authorization: token ${GH_PAT}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/airbnb/viaduct
            echo "✅ Access to private repository"

      - run:
          name: Checking conection to Github Cloud 
          command: |
            URL="https://api.github.com/repos/airbnb/viaduct"
            code=$(curl -sS -D /tmp/headers.txt -o /tmp/body.json -w "%{http_code}" \
              -H "Authorization: Bearer ${GH_PAT}" \
              -H "Accept: application/vnd.github+json" "$URL")
            echo "== Response headers =="; cat /tmp/headers.txt
            echo "== Body =="; (jq . /tmp/body.json || cat /tmp/body.json)
            echo "HTTP $code"
            if [ "$code" = "200" ]; then
              echo "✅ Access to to Github Cloud repository"
            fi
            test "${code:0:1}" = "2"

      - run:
          name: Checking conection to Github Enterprise
          command: |
            URL="https://git.musta.ch/api/v3/repos/airbnb/treehouse"
            code=$(curl -sS -D /tmp/headers.txt -o /tmp/body.json -w "%{http_code}" \
              -H "Authorization: Bearer ${GH_PAT_TREEHOUSE}" \
              -H "Accept: application/vnd.github+json" "$URL")
            echo "== Response headers =="; cat /tmp/headers.txt
            echo "== Body =="; (jq . /tmp/body.json || cat /tmp/body.json)
            echo "HTTP $code"
            if [ "$code" = "200" ]; then
              echo "✅ Access to Github Enterprise repository"
            fi
            test "${code:0:1}" = "2"


 
