version: 2.1

workflows:
  build-workflow:
    jobs:
      - runner
jobs:
  runner:
    machine: true
    resource_class: gperalta-primehire/gperalta-self-hosted
    steps:
      - run: echo "Hi I'm on Runners!"
      - run:
          name: Checking conection to Github Cloud 
          command: |
            curl -f \
              -H "Authorization: token ${GH_PAT}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/airbnb/viaduct
            echo "✅ Access to private repository"

      - run:
          name: Check connection to GitHub On-Premise
          command: |
            set -euo pipefail
            HTTP_CODE=$(curl -sS \
              -H "Authorization: token ${GH_PAT_TREEHOUSE}" \
              -H "Accept: application/vnd.github.v3+json" \
              -o /tmp/resp.json \
              -w '%{http_code}' \
              https://git.musta.ch/api/v1/airbnb/treehouse/)
            (jq . /tmp/resp.json || cat /tmp/resp.json)
            echo "HTTP ${HTTP_CODE}"
            test "${HTTP_CODE}" -ge 200 -a "${HTTP_CODE}" -lt 300
            echo "✅ Access to private repository"


