package viaduct.service

import viaduct.apiannotations.StableApi
import viaduct.service.api.Viaduct
import viaduct.service.api.spi.NaiveTenantModuleInjectorFactory
import viaduct.service.api.spi.TenantModuleInjectorFactory

/**
 * A simpler factory for creating [Viaduct] instances with sensible defaults.
 *
 * Use this when you do not need fine-grained control over SPI implementations such as
 * error reporting, metrics, or exception handling. For full control, use [ViaductBuilder].
 *
 * @see ViaductBuilder
 */
@StableApi
object BasicViaductFactory {
    /**
     * A simple factory-function for [Viaduct] instances.
     *
     * Discovers tenant modules from resources files generated by the viaduct-module plugin at build time.
     *
     * @param tenantModuleInjectorFactory factory used for tenant modules discovered from the
     *        classpath. Defaults to [NaiveTenantModuleInjectorFactory].
     * @param scopedSchemas scoped schema definitions to register. Defaults to none (only the
     *        full schema is available).
     */
    @JvmStatic
    @JvmOverloads
    fun create(
        tenantModuleInjectorFactory: TenantModuleInjectorFactory = NaiveTenantModuleInjectorFactory,
        scopedSchemas: List<SchemaScopeInfo> = emptyList(),
    ): Viaduct =
        ViaductBuilder()
            .withTenantModuleInjectorFactory(tenantModuleInjectorFactory)
            .withScopedSchemas(scopedSchemas)
            .build()
}
