package viaduct.service

import viaduct.api.bootstrap.ViaductTenantAPIBootstrapper
import viaduct.apiannotations.ExperimentalApi
import viaduct.apiannotations.StableApi
import viaduct.apiannotations.VisibleForTest
import viaduct.engine.BootstrapperFactory
import viaduct.engine.api.spi.LegacyTenantModuleBootstrapper
import viaduct.engine.api.spi.ProxyResolverFactory
import viaduct.service.api.SchemaId
import viaduct.service.api.Viaduct
import viaduct.service.api.spi.CodeInjector
import viaduct.service.api.spi.NaiveTenantModuleBootstrapper
import viaduct.service.api.spi.SharedTenantModuleBootstrapper
import viaduct.service.api.spi.TenantAPIBootstrapperBuilder
import viaduct.service.api.spi.TenantModuleBootstrapper
import viaduct.service.runtime.SchemaConfiguration
import viaduct.service.runtime.StandardViaduct

/**
 * A simpler factory for creating [Viaduct] instances with sensible defaults.
 *
 * Use this when you do not need fine-grained control over SPI implementations such as
 * error reporting, metrics, or exception handling. For full control, use [ViaductBuilder].
 *
 * @see ViaductBuilder
 */
@StableApi
object BasicViaductFactory {
    /**
     * A simple factory-function for [Viaduct] instances.
     *
     * Discovers tenant modules from resources files generated by the viaduct-module plugin at build time.     *
     *
     * @param schemaRegistrationInfo schemas available for serving. Defaults to the full schema only.
     * @param tenantRegistrationInfo injector used to instantiate resolver classes.
     */
    @JvmOverloads
    fun create(
        schemaRegistrationInfo: SchemaRegistrationInfo = SchemaRegistrationInfo(),
        tenantRegistrationInfo: TenantRegistrationInfo,
    ): Viaduct = createWithProxy(schemaRegistrationInfo, tenantRegistrationInfo, ProxyResolverFactory.NO_OP)

    @ExperimentalApi
    fun create(
        schemaRegistrationInfo: SchemaRegistrationInfo = SchemaRegistrationInfo(),
        tenantRegistrationInfo: TenantRegistrationInfo,
        proxyResolverFactory: ProxyResolverFactory,
    ): Viaduct = createWithProxy(schemaRegistrationInfo, tenantRegistrationInfo, proxyResolverFactory)

    private fun createWithProxy(
        schemaRegistrationInfo: SchemaRegistrationInfo,
        tenantRegistrationInfo: TenantRegistrationInfo,
        proxyResolverFactory: ProxyResolverFactory,
    ): Viaduct =
        createFromResource(
            schemaRegistrationInfo = schemaRegistrationInfo,
            tenantModuleBootstrapper = SharedTenantModuleBootstrapper(tenantRegistrationInfo.tenantCodeInjector),
            proxyResolverFactory = proxyResolverFactory,
        )

    /**
     * Factory function for [Viaduct] instances that bootstrap tenant modules from
     * pre-generated registry JSON files at META-INF/viaduct/modules/ on the classpath.
     *
     * Tenant configuration comes entirely from the JSON files — no [TenantRegistrationInfo] needed.
     *
     * @param tenantModuleBootstrapper bootstrapper used for tenant modules discovered from the
     *        classpath. Defaults to [NaiveTenantModuleBootstrapper]. Use
     *        [SharedTenantModuleBootstrapper] when all tenants should share a single custom injector.
     * @param proxyResolverFactory factory for wrapping resolvers with proxies (e.g., for remote execution).
     *        Defaults to [ProxyResolverFactory.NO_OP], which leaves all resolvers executing locally.
     */
    @JvmOverloads
    fun createFromResource(
        schemaRegistrationInfo: SchemaRegistrationInfo = SchemaRegistrationInfo(),
        tenantModuleBootstrapper: TenantModuleBootstrapper = NaiveTenantModuleBootstrapper,
        proxyResolverFactory: ProxyResolverFactory = ProxyResolverFactory.NO_OP,
    ): Viaduct {
        val bootstrapperBuilder = object : TenantAPIBootstrapperBuilder<LegacyTenantModuleBootstrapper> {
            override fun create() = BootstrapperFactory.fromResources(tenantModuleBootstrapper)
        }

        return StandardViaduct.Builder()
            .withTenantAPIBootstrapperBuilder(bootstrapperBuilder)
            .withProxyResolverFactory(proxyResolverFactory)
            .withSchemaConfiguration(applySchemaRegistry(schemaRegistrationInfo))
            .build()
    }

    /**
     * Test-only factory function for [Viaduct] instances that allows overriding GRT schema discovery settings.
     *
     * This method should only be used in tests that need to override the default GRT package prefix
     * or resource pattern. Production code should use [create] which relies on default GRT discovery.
     *
     * @param scopes schemas available for serving.  By default, only the full schema is available.
     * @param tenantRegistrationInfo tenant configuration including package prefix and injector.
     * @param grtPackagePrefix package prefix for GRT schema file discovery (test override only).
     * @param grtResourcesIncluded regex pattern for GRT schema files (test override only).
     */
    @VisibleForTest
    fun createForTesting(
        scopes: List<SchemaScopeInfo> = listOf(),
        tenantRegistrationInfo: TenantRegistrationInfo,
        grtPackagePrefix: String? = null,
        grtResourcesIncluded: String? = null,
    ): Viaduct {
        val schemaRegistrationInfo = SchemaRegistrationInfo(
            scopes = scopes,
            grtPackagePrefix = grtPackagePrefix,
            grtResourcesIncluded = grtResourcesIncluded
        )
        val builder = builderWithTenantInfo(tenantRegistrationInfo)
        val schemaConfiguration = applySchemaRegistry(schemaRegistrationInfo)
        return builder.withSchemaConfiguration(schemaConfiguration).build()
    }

    // internal for testing
    internal fun builderWithTenantInfo(tenantRegistrationInfo: TenantRegistrationInfo): StandardViaduct.Builder =
        StandardViaduct.Builder()
            .withTenantAPIBootstrapperBuilder(
                ViaductTenantAPIBootstrapper.Builder()
                    .tenantPackagePrefix(tenantRegistrationInfo.tenantPackagePrefix)
                    .tenantCodeInjector(tenantRegistrationInfo.tenantCodeInjector)
            )

    // internal for testing
    internal fun applySchemaRegistry(schemaRegistrationInfo: SchemaRegistrationInfo): SchemaConfiguration {
        val scopeConfigs = schemaRegistrationInfo.scopes.map { scope ->
            if (scope.scopesToApply.isNullOrEmpty()) {
                SchemaConfiguration.ScopeConfig(scope.schemaId, emptySet())
            } else {
                SchemaConfiguration.ScopeConfig(scope.schemaId, scope.scopesToApply)
            }
        }

        return SchemaConfiguration.fromResources(
            grtPackagePrefix = schemaRegistrationInfo.grtPackagePrefix,
            resourcesIncluded = schemaRegistrationInfo.grtResourcesIncluded?.toRegex(),
            scopes = scopeConfigs.toSet()
        )
    }
}

/**
 * Configuration for a tenant, specifying how to discover and instantiate tenant code.
 *
 * @param tenantPackagePrefix the package prefix under which tenant-generated code is found
 * @param tenantCodeInjector the injector used to instantiate resolver and other tenant classes;
 *        defaults to [CodeInjector.Naive] which uses reflection with zero-arg constructors
 */
@StableApi
data class TenantRegistrationInfo(
    val tenantPackagePrefix: String,
    val tenantCodeInjector: CodeInjector = CodeInjector.Naive,
)

/**
 * A descriptor for a (scoped) schema to be registered into a [Viaduct] engine.
 *
 * @param scopes The set of scope defining parameters
 * @param grtPackagePrefix the package prefix to search for GRT schema (.graphqls) files.
 *        For testing only - production should use null to rely on default discovery.
 * @param grtResourcesIncluded the regex to match GRT schema files to include.
 *        For testing only - production should use null to rely on default pattern.
 *
 */
@StableApi
data class SchemaRegistrationInfo(
    val scopes: List<SchemaScopeInfo> = listOf(),
    val grtPackagePrefix: String? = null,
    val grtResourcesIncluded: String? = null,
)

/**
 * A descriptor for a scoped schema configuration.
 *
 * @param schemaId The id for the scoped schema
 * @param scopesToApply The set of scope-ids that define the scoped schema.
 *                      If null or empty, the full schema is used.
 */
@StableApi
data class SchemaScopeInfo(
    val schemaId: String = "",
    val scopesToApply: Set<String>? = null,
)

/** Converts this [SchemaId.Scoped] to a [SchemaScopeInfo] for use with [BasicViaductFactory]. */
@StableApi
fun SchemaId.Scoped.toSchemaScopeInfo(): SchemaScopeInfo = SchemaScopeInfo(this.id, this.scopeIds.ifEmpty { null })
