interface Node {
  id: ID!
}

interface GeneratedInterface {
  common: String!
}

type Hash {
  nested: Hash
  hash: Int!
}

type Object0 implements GeneratedInterface {
  field0: Object1!
  field1: [Int!]!
  field2: [Float!]!
  field3: [String!]!
  field4: Int!
  field5: Boolean!
  field6: [Int!]!
  field7(arg: Int!, arg1: String, arg2: [Float!]!): Object9!
  field8: [Float]!
  field9: [Float!]!
  field10: Int!
  field11(arg: String!): Int!
  field12: [Boolean!]
  field13: [String!]!
  field14: Float!
  field15: [ID!]!
  field16: Object4!
  field17: Float!
  common: String!
  hash: Hash!
}

type Object1 {
  field0: Object2!
  field1: ID!
  field2: Boolean
  field3(arg: Int!, arg1: String!): [Int]!
  field4: [Float!]!
  field5: String!
  field6: Float!
  field7: String!
  field8: Boolean!
  field9: String!
  field10: Int!
  field11: ID!
  field12: Boolean!
  field13: String!
  field14: [Boolean!]!
  field15: [String!]!
  field16: [Object1!]!
  field17: [Boolean!]!
  hash: Hash!
}

type Object2 implements GeneratedInterface {
  field0: Object3!
  field1: Boolean!
  field2: [ID!]!
  field3: Boolean!
  field4: [Float!]!
  field5: ID!
  field6: Boolean!
  field7: [String!]
  field8: Float!
  field9(arg: Float!): Int!
  field10: [Object3!]!
  field11: Float!
  field12: [Boolean!]!
  field13: Object5
  field14(arg: String, arg1: Float, arg2: Float!): Boolean
  field15: Int!
  common(implementationDefault: Int = 7): String!
  hash: Hash!
}

type Object3 implements GeneratedInterface {
  field0: Object4!
  field1: [String!]!
  field2: String!
  field3: Int!
  field4: [Float!]!
  field5: String!
  field6: [Boolean!]!
  field7: [Int!]
  field8: Object2
  field9: ID
  field10: Object12!
  field11: [ID!]!
  field12: String!
  field13: [Float!]!
  field14: [String]!
  common: String!
  hash: Hash!
}

type Object4 {
  field0: Object5!
  field1(arg: Int!): [Int!]!
  field2: Float!
  field3: String!
  field4: [Boolean!]!
  field5: Boolean!
  field6: Int!
  field7: String!
  field8: [Int!]!
  field9: String!
  field10: ID!
  field11: Int
  field12: Boolean
  field13: [String!]!
  field14: String!
  hash: Hash!
}

type Object5 implements Node {
  id: ID!
  field0: Object6!
  field1: [Object11!]!
  field2: ID!
  field3(arg: String!): [Int!]!
  field4: [Float]!
  field5: [ID!]!
  field6: [String!]!
  field7: [String!]
  field8: String!
  field9: [Int!]!
  field10: ID!
  field11: Int!
  field12: [String!]!
  field13: Boolean!
  hash: Hash!
}

type Object6 implements Node {
  id: ID!
  field0: Object7!
  field1: Int!
  field2: [String]!
  field3(arg: Float!, arg1: ID!): ID
  field4: Int!
  field5: ID!
  field6: ID!
  field7: [Int!]!
  field8: [Boolean!]!
  field9(arg: String!): Boolean!
  field10: [String!]!
  field11: [Boolean!]!
  field12: ID
  field13: [Int!]!
  field14: [Boolean!]!
  hash: Hash!
}

type Object7 implements GeneratedInterface {
  field0: [ID!]!
  field1: Boolean!
  field2: [Object12]!
  field3: [Float!]!
  field4: Boolean
  field5: Float!
  field6: ID!
  field7: Float!
  field8: Boolean
  field9: Boolean
  field10: [Boolean!]!
  field11: [Boolean!]!
  field12: [Object12!]!
  field13: [Object8!]!
  field14: Float!
  field15: Object12
  field16: [ID!]
  field17: Boolean!
  common: String!
  hash: Hash!
}

type Object8 implements GeneratedInterface {
  field0: [ID!]!
  field1: ID!
  field2: ID!
  field3: Object9!
  field4: [Boolean!]!
  field5: [ID!]!
  field6: [Int!]!
  field7: Object9
  field8: [Boolean]!
  field9(arg: Boolean!): Int
  field10: [Float!]!
  field11: [ID]!
  field12(arg: Int!, arg1: Int!, arg2: Int!): [Object9!]
  field13: String!
  field14: [Object5!]!
  field15: [String!]!
  field16: String!
  common: String!
  hash: Hash!
}

type Object9 implements Node {
  id: ID!
  field0(arg: [ID!]!): Boolean!
  field1: [Int]!
  field2: Int!
  field3: [String!]!
  field4: Boolean!
  field5: Object10!
  field6: Boolean!
  field7: String!
  field8: Object12!
  field9: Object10
  field10: [Float!]!
  field11: Float!
  field12(arg: [String!], arg1: Int): [String!]!
  field13: [Float!]
  hash: Hash!
}

type Object10 implements GeneratedInterface {
  field0: [String!]!
  field1: ID!
  field2: [String]!
  field3: String!
  field4: Float!
  field5: [Float!]!
  field6: ID!
  field7: Float
  field8(arg: Float!): Object11!
  field9: Boolean!
  field10: [Float]!
  field11: [Boolean]!
  field12: Int!
  field13(arg: Float): Object1
  field14(arg: Float!, arg1: ID!, arg2: ID!): Float!
  field15: [String!]!
  field16: [String!]!
  field17: ID!
  common: String!
  hash: Hash!
}

type Object11 {
  field0: Object12!
  field1: Float!
  field2: Int!
  field3: [Boolean!]!
  field4: Boolean!
  field5: [Float]
  field6: Int!
  field7: [Float!]
  field8: [Boolean!]!
  field9: Boolean!
  field10: Float!
  field11: [Int!]!
  field12: [Int]
  field13: Object12!
  field14(arg: Int, arg1: String!): String
  hash: Hash!
}

type Object12 implements GeneratedInterface {
  field0: ID!
  field1: [Boolean!]
  field2: Object2
  field3: [Boolean!]!
  field4: [Boolean!]
  field5: [String]!
  field6: Int!
  field7: [Boolean!]!
  field8: Float!
  field9: String
  field10: [Int!]
  field11(arg: Float!, arg1: Float!, arg2: Boolean!): [Boolean!]
  field12: Int
  field13: Boolean
  field14: [ID!]!
  field15: [Int!]
  field16: String!
  field17: [String]!
  common(implementationDefault: Int = 7): String!
  hash: Hash!
}

union GeneratedUnion = Object0 | Object1 | Object2 | Object3 | Object4 | Object10 | Object11 | Object12

type Query {
  query0: Object0!
  query1(arg: String!): Object12
  query2: Float!
  query3: [Boolean!]!
  query4: [GeneratedUnion!]!
  query5: [Object3!]!
  query6(arg: Float!, arg1: ID!): Object8
  query7: [Object6]!
  query8: Node
  query9: Object10!
  query10: [GeneratedInterface!]!
  query11: Float!
  query12: Object2!
}
