package viaduct.graphql.schema.validation

/**
 * Standard error codes for schema validation rules.
 *
 * Using constants ensures consistency and enables IDE support for
 * code completion and refactoring.
 */
object ValidationErrorCodes {
    // NoSubscriptionsRule
    const val SUBSCRIPTION_NOT_ALLOWED = "SUBSCRIPTION_NOT_ALLOWED"

    // NoCustomScalarsRule
    const val CUSTOM_SCALAR_NOT_ALLOWED = "CUSTOM_SCALAR_NOT_ALLOWED"

    // ApplicationOnlyDefinitionsRule
    const val DIRECTIVE_DEFINED_IN_MODULE = "DIRECTIVE_DEFINED_IN_MODULE"
    const val SCALAR_DEFINED_IN_MODULE = "SCALAR_DEFINED_IN_MODULE"

    // BackingDataFieldsRule
    const val BACKING_DATA_MISSING_DIRECTIVE = "BACKING_DATA_MISSING_DIRECTIVE"
    const val BACKING_DATA_MISSING_TYPE = "BACKING_DATA_MISSING_TYPE"
    const val BACKING_DATA_ON_INPUT_FIELD = "BACKING_DATA_ON_INPUT_FIELD"

    // IdOfTypeValidationRule
    const val ID_OF_TYPE_NOT_FOUND = "ID_OF_TYPE_NOT_FOUND"
    const val ID_OF_TYPE_NOT_NODE = "ID_OF_TYPE_NOT_NODE"

    // NamespaceTypeConstraintsRule
    const val NAMESPACE_TYPE_FIELD_HAS_ARGS = "NAMESPACE_TYPE_FIELD_HAS_ARGS"
    const val NAMESPACE_TYPE_FIELD_IS_LIST = "NAMESPACE_TYPE_FIELD_IS_LIST"
    const val NAMESPACE_TYPE_FIELD_IS_NON_NULL = "NAMESPACE_TYPE_FIELD_IS_NON_NULL"
    const val NAMESPACE_TYPE_IN_UNION = "NAMESPACE_TYPE_IN_UNION"
    const val NAMESPACE_TYPE_PARENT_COUNT_NOT_ONE = "NAMESPACE_TYPE_PARENT_COUNT_NOT_ONE"
    const val NAMESPACE_TYPE_INVALID_PARENT = "NAMESPACE_TYPE_INVALID_PARENT"

    // ConnectionTypeStructureRule
    const val CONNECTION_MISSING_EDGES_FIELD = "CONNECTION_MISSING_EDGES_FIELD"
    const val CONNECTION_EDGES_TYPE_NOT_EDGE = "CONNECTION_EDGES_TYPE_NOT_EDGE"
    const val CONNECTION_MISSING_PAGE_INFO_FIELD = "CONNECTION_MISSING_PAGE_INFO_FIELD"
    const val CONNECTION_PAGE_INFO_MUST_BE_NON_NULL = "CONNECTION_PAGE_INFO_MUST_BE_NON_NULL"

    // ConnectionEdgeStructureRule
    const val EDGE_MISSING_NODE_FIELD = "EDGE_MISSING_NODE_FIELD"

    // ConnectionPageInfoRule
    const val PAGE_INFO_MISSING_REQUIRED_FIELD = "PAGE_INFO_MISSING_REQUIRED_FIELD"
    const val PAGE_INFO_BOOLEAN_FIELD_MUST_BE_NON_NULL_BOOLEAN = "PAGE_INFO_BOOLEAN_FIELD_MUST_BE_NON_NULL_BOOLEAN"
    const val PAGE_INFO_CURSOR_MUST_BE_NULLABLE = "PAGE_INFO_CURSOR_MUST_BE_NULLABLE"

    // ConnectionArgumentsNullabilityRule
    const val CONNECTION_ARG_MUST_BE_NULLABLE = "CONNECTION_ARG_MUST_BE_NULLABLE"

    // NoCrossModuleInputExtensionsRule
    const val CROSS_MODULE_INPUT_EXTENSION = "CROSS_MODULE_INPUT_EXTENSION"

    // StructuralDirectivesOnBaseTypeRule
    const val STRUCTURAL_DIRECTIVE_ON_EXTENSION = "STRUCTURAL_DIRECTIVE_ON_EXTENSION"

    // CrossModuleExtensionFieldsResolverRule
    const val CROSS_MODULE_EXTENSION_FIELD_MISSING_RESOLVER = "CROSS_MODULE_EXTENSION_FIELD_MISSING_RESOLVER"
}
