package viaduct.arbitrary.graphql

import graphql.language.AstPrinter
import graphql.schema.idl.SchemaPrinter
import viaduct.engine.api.Coordinate
import viaduct.engine.api.RequiredSelectionSet
import viaduct.engine.api.VariablesResolver
import viaduct.engine.api.ViaductSchema
import viaduct.engine.api.spi.CheckerExecutor
import viaduct.engine.api.spi.FieldResolverExecutor
import viaduct.engine.api.spi.NodeResolverExecutor
import viaduct.graphql.utils.ParsedSelections
import viaduct.graphql.utils.SelectionsParserUtils.EntryPointFragmentName
import viaduct.service.api.SchemaId
import viaduct.service.api.Viaduct
import viaduct.service.runtime.StandardViaduct

/**
 * Human-readable snapshot of a Viaduct instance generated by the arbitrary GraphQL utilities.
 */
internal class ViaductDescriptor(
    private val schemas: List<SchemaDescriptor>,
    private val fieldResolvers: List<FieldResolverDescriptor> = emptyList(),
    private val nodeResolvers: List<NodeResolverDescriptor> = emptyList(),
    private val checkers: List<CheckerDescriptor> = emptyList(),
) {
    data class SchemaDescriptor(
        val schemaId: String,
        val sdl: String,
    )

    data class FieldResolverDescriptor(
        val coordinate: Coordinate,
        val resolverId: String,
        val className: String,
        val isBatching: Boolean,
        val isSelective: Boolean,
        val objectSelectionSet: RequiredSelectionSetDescriptor?,
        val querySelectionSet: RequiredSelectionSetDescriptor?,
    )

    data class NodeResolverDescriptor(
        val typeName: String,
        val className: String,
        val isBatching: Boolean,
        val isSelective: Boolean,
    )

    data class CheckerDescriptor(
        val coordinate: String,
        val className: String,
        val requiredSelectionSets: List<NamedRequiredSelectionSetDescriptor>,
    )

    data class NamedRequiredSelectionSetDescriptor(
        val name: String,
        val requiredSelectionSet: RequiredSelectionSetDescriptor?,
    )

    data class RequiredSelectionSetDescriptor(
        val typeName: String,
        val forChecker: Boolean,
        val selections: String,
        val variablesResolvers: List<VariablesResolverDescriptor>,
        val alreadyDescribed: Boolean = false,
    ) {
        override fun toString(): String = renderRequiredSelectionSetDescriptor()
    }

    data class VariablesResolverDescriptor(
        val variableNames: Set<String>,
        val className: String,
        val requiredSelectionSet: RequiredSelectionSetDescriptor?,
    ) {
        override fun toString(): String = renderVariablesResolverDescriptor()
    }

    override fun toString(): String =
        buildString {
            line("Viaduct Descriptor")

            section("schemas", schemas) { schema ->
                line("  - ${schema.schemaId}")
                block("      ", schema.sdl)
            }

            section("field resolvers", fieldResolvers) { resolver ->
                line("  - ${resolver.coordinate.asString()}")
                line("      resolverId: ${resolver.resolverId}")
                line("      class: ${resolver.className}")
                line("      isBatching: ${resolver.isBatching}")
                line("      isSelective: ${resolver.isSelective}")
                appendRequiredSelectionSetDescriptor("      objectSelectionSet", resolver.objectSelectionSet)
                appendRequiredSelectionSetDescriptor("      querySelectionSet", resolver.querySelectionSet)
            }

            section("node resolvers", nodeResolvers) { resolver ->
                line("  - ${resolver.typeName}")
                line("      class: ${resolver.className}")
                line("      isBatching: ${resolver.isBatching}")
                line("      isSelective: ${resolver.isSelective}")
            }

            section("checkers", checkers) { checker ->
                line("  - ${checker.coordinate}")
                line("      class: ${checker.className}")
                if (checker.requiredSelectionSets.isEmpty()) {
                    line("      requiredSelectionSets: <none>")
                } else {
                    line("      requiredSelectionSets:")
                    checker.requiredSelectionSets.forEach { named ->
                        appendRequiredSelectionSetDescriptor("        ${named.name}", named.requiredSelectionSet)
                    }
                }
            }
        }.trimEnd()

    private fun <T> StringBuilder.section(
        title: String,
        values: List<T>,
        render: StringBuilder.(T) -> Unit,
    ) {
        line()
        line("$title:")
        if (values.isEmpty()) {
            line("  <none>")
        } else {
            values.forEach { render(it) }
        }
    }

    private fun StringBuilder.block(
        indent: String,
        text: String,
    ) {
        text.lineSequence()
            .filter { it.isNotBlank() }
            .forEach { line("$indent$it") }
    }

    private fun StringBuilder.line(text: String = "") {
        append(text).append('\n')
    }

    companion object {
        private val schemaPrinter = SchemaPrinter()

        internal fun from(viaduct: Viaduct): ViaductDescriptor = checkNotNull(viaduct as? DescribedViaduct).descriptor.value

        internal fun from(requiredSelectionSet: RequiredSelectionSet): RequiredSelectionSetDescriptor = describeRequiredSelectionSet(requiredSelectionSet, mutableSetOf())

        internal fun from(variablesResolver: VariablesResolver): VariablesResolverDescriptor = describeVariablesResolver(variablesResolver, mutableSetOf())

        internal fun fromGenerated(
            viaduct: Viaduct,
            config: GeneratedViaductDescriptorConfig,
        ): ViaductDescriptor =
            ViaductDescriptor(
                schemas = (viaduct as? StandardViaduct)?.schemaDescriptors()
                    ?: listOf(SchemaDescriptor(SchemaId.Full.toString(), schemaPrinter.print(config.schema.schema))),
                fieldResolvers = config.fieldResolverExecutors
                    .sortedBy { it.first.asString() }
                    .map { (coord, executor) -> executor.describe(coord) },
                nodeResolvers = config.nodeResolverExecutors
                    .sortedBy { it.first }
                    .map { (_, executor) -> executor.describe },
                checkers = (
                    config.fieldCheckerExecutors.map { (coord, executor) -> "field ${coord.asString()}" to executor } +
                        config.typeCheckerExecutors.map { (typeName, executor) -> "type $typeName" to executor }
                )
                    .sortedBy { it.first }
                    .map { (coordinate, executor) -> executor.describe(coordinate) },
            )

        private fun StandardViaduct.schemaDescriptors(): List<SchemaDescriptor> =
            engineRegistry.getRegisteredSchemaIds()
                .sortedBy { it.toString() }
                .map { schemaId ->
                    SchemaDescriptor(
                        schemaId = schemaId.toString(),
                        sdl = schemaPrinter.print(getSchema(schemaId).schema),
                    )
                }

        private fun FieldResolverExecutor.describe(coord: Coordinate): FieldResolverDescriptor =
            FieldResolverDescriptor(
                coordinate = coord,
                resolverId = resolverId,
                className = debugClassName(),
                isBatching = isBatching,
                isSelective = isSelective,
                objectSelectionSet = objectSelectionSet?.describeWithFreshContext(),
                querySelectionSet = querySelectionSet?.describeWithFreshContext(),
            )

        private val NodeResolverExecutor.describe: NodeResolverDescriptor
            get() =
                NodeResolverDescriptor(
                    typeName = typeName,
                    className = debugClassName(),
                    isBatching = isBatching,
                    isSelective = isSelective,
                )

        private fun CheckerExecutor.describe(coordinate: String): CheckerDescriptor =
            CheckerDescriptor(
                coordinate = coordinate,
                className = debugClassName(),
                requiredSelectionSets = requiredSelectionSets
                    .toSortedMap()
                    .map { (name, rss) ->
                        NamedRequiredSelectionSetDescriptor(name, rss?.describeWithFreshContext())
                    },
            )

        private fun RequiredSelectionSet.describeWithFreshContext(): RequiredSelectionSetDescriptor = describeRequiredSelectionSet(this, mutableSetOf())

        private fun describeRequiredSelectionSet(
            rss: RequiredSelectionSet,
            seen: MutableSet<RequiredSelectionSet.Id>,
        ): RequiredSelectionSetDescriptor {
            val alreadyDescriptored = !seen.add(rss.id)
            return RequiredSelectionSetDescriptor(
                typeName = rss.selections.typeName,
                forChecker = rss.forChecker,
                selections = rss.selections.describe(),
                variablesResolvers = if (alreadyDescriptored) {
                    emptyList()
                } else {
                    rss.variablesResolvers.map { describeVariablesResolver(it, seen) }
                },
                alreadyDescribed = alreadyDescriptored,
            )
        }

        private fun describeVariablesResolver(
            variablesResolver: VariablesResolver,
            seen: MutableSet<RequiredSelectionSet.Id>,
        ): VariablesResolverDescriptor =
            VariablesResolverDescriptor(
                variableNames = variablesResolver.variableNames,
                className = variablesResolver.debugClassName(),
                requiredSelectionSet = variablesResolver.requiredSelectionSet?.let {
                    describeRequiredSelectionSet(it, seen)
                },
            )

        private fun Coordinate.asString(): String = "$first.$second"

        private fun Any.debugClassName(): String = this::class.qualifiedName ?: this::class.java.name
    }
}

internal fun RequiredSelectionSet.describe(): ViaductDescriptor.RequiredSelectionSetDescriptor = ViaductDescriptor.from(this)

internal fun VariablesResolver.describe(): ViaductDescriptor.VariablesResolverDescriptor = ViaductDescriptor.from(this)

internal data class GeneratedViaductDescriptorConfig(
    val schema: ViaductSchema,
    val fieldResolverExecutors: List<Pair<Coordinate, FieldResolverExecutor>>,
    val nodeResolverExecutors: List<Pair<String, NodeResolverExecutor>>,
    val fieldCheckerExecutors: Map<Coordinate, CheckerExecutor>,
    val typeCheckerExecutors: Map<String, CheckerExecutor>,
)

internal class DescribedViaduct(
    private val delegate: Viaduct,
    val descriptor: Lazy<ViaductDescriptor>
) : Viaduct by delegate

private fun ViaductDescriptor.RequiredSelectionSetDescriptor.renderRequiredSelectionSetDescriptor(): String =
    buildString {
        appendRequiredSelectionSetDescriptor(this@renderRequiredSelectionSetDescriptor, "")
    }.trimEnd()

private fun ViaductDescriptor.VariablesResolverDescriptor.renderVariablesResolverDescriptor(): String =
    buildString {
        appendVariablesResolverDescriptor(this@renderVariablesResolverDescriptor, "")
    }.trimEnd()

private fun StringBuilder.appendRequiredSelectionSetDescriptor(
    label: String,
    rss: ViaductDescriptor.RequiredSelectionSetDescriptor?,
) {
    if (rss == null) {
        line("$label: <none>")
        return
    }

    line("$label:")
    appendRequiredSelectionSetDescriptor(rss, label.leadingWhitespace() + "  ")
}

private fun StringBuilder.appendRequiredSelectionSetDescriptor(
    rss: ViaductDescriptor.RequiredSelectionSetDescriptor,
    indent: String,
) {
    line("${indent}type: ${rss.typeName}")
    line("${indent}forChecker: ${rss.forChecker}")
    if (rss.alreadyDescribed) {
        line("${indent}selections: <already described>")
        return
    }

    line("${indent}selections:")
    block("$indent  ", rss.selections)
    if (rss.variablesResolvers.isEmpty()) {
        line("${indent}variablesResolvers: <none>")
    } else {
        line("${indent}variablesResolvers:")
        rss.variablesResolvers.forEach { resolver ->
            appendVariablesResolverDescriptor(resolver, "$indent  ")
        }
    }
}

private fun StringBuilder.appendVariablesResolverDescriptor(
    resolver: ViaductDescriptor.VariablesResolverDescriptor,
    indent: String,
) {
    line("$indent- variables: ${resolver.variableNames.sorted()}")
    line("$indent  class: ${resolver.className}")
    appendRequiredSelectionSetDescriptor("$indent  requiredSelectionSet", resolver.requiredSelectionSet)
}

private fun ParsedSelections.describe(): String =
    buildString {
        append(AstPrinter.printAst(selections).trim())
        val fragments = fragmentMap.values
            .filter { it.name != EntryPointFragmentName }
            .sortedBy { it.name }
        if (fragments.isNotEmpty()) {
            if (isNotEmpty()) append('\n')
            append("fragments:\n")
            fragments.forEach { fragment ->
                append(AstPrinter.printAst(fragment).trim()).append('\n')
            }
        }
    }.trimEnd()

private fun String.leadingWhitespace(): String = takeWhile { it == ' ' }

private fun StringBuilder.block(
    indent: String,
    text: String,
) {
    text.lineSequence()
        .filter { it.isNotBlank() }
        .forEach { line("$indent$it") }
}

private fun StringBuilder.line(text: String = "") {
    append(text).append('\n')
}
