package viaduct.arbitrary.cli

import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.types.file
import com.github.ajalt.clikt.parameters.types.long
import graphql.schema.idl.SchemaParser
import graphql.schema.idl.SchemaPrinter
import io.kotest.property.Arb
import io.kotest.property.RandomSource
import io.kotest.property.arbitrary.next
import java.io.File
import kotlin.random.Random
import viaduct.arbitrary.common.CompoundingWeight
import viaduct.arbitrary.common.Config
import viaduct.arbitrary.graphql.AppliedDirectiveWeight
import viaduct.arbitrary.graphql.BanFieldNames
import viaduct.arbitrary.graphql.DefaultValueWeight
import viaduct.arbitrary.graphql.DescriptionLength
import viaduct.arbitrary.graphql.DirectiveHasArgs
import viaduct.arbitrary.graphql.EnumTypeSize
import viaduct.arbitrary.graphql.FieldArgumentWeight
import viaduct.arbitrary.graphql.GenInterfaceStubsIfNeeded
import viaduct.arbitrary.graphql.IncludeBuiltinDirectives
import viaduct.arbitrary.graphql.InputObjectTypeSize
import viaduct.arbitrary.graphql.InterfaceImplementsInterface
import viaduct.arbitrary.graphql.InterfaceTypeSize
import viaduct.arbitrary.graphql.ObjectImplementsInterface
import viaduct.arbitrary.graphql.ObjectTypeSize
import viaduct.arbitrary.graphql.OneOfTypeWeight
import viaduct.arbitrary.graphql.SchemaSize
import viaduct.arbitrary.graphql.TypeType
import viaduct.arbitrary.graphql.TypeTypeWeights
import viaduct.arbitrary.graphql.UnionTypeSize
import viaduct.arbitrary.graphql.builtinScalarNames
import viaduct.arbitrary.graphql.graphQLTypes

/** Generates an arbitrary GraphQL schema (SDL) and writes it to a file; invoked out-of-process so consumers avoid a compile-time dependency on `shared/arbitrary`. */
class GenerateSchema : CliktCommand(name = "generate-schema") {
    object Main {
        @JvmStatic
        fun main(args: Array<String>) = GenerateSchema().main(args)
    }

    private val output: File by option("--output", help = "File to write the generated SDL to")
        .file(mustExist = false, canBeDir = false)
        .required()

    private val seed: Long? by option(
        "--seed",
        help = "Seed for reproducible generation. If omitted, a random seed is chosen and printed."
    ).long()

    /**
     * Maximizes schema "arbitrariness" so the generated fragment is a good stress test for
     * consumers that splice it into an existing schema: every TypeType is represented, every
     * interface is guaranteed an implementing object, and type/field counts are large.
     *
     * [IncludeBuiltinDirectives] and custom scalars (left at their `false` default) stay off
     * because the fragment is merged into a schema that already declares its own directives and
     * can't declare custom scalars.
     *
     * [DefaultValueWeight] and [DirectiveHasArgs] stay off: `ScalarValueGen` can't synthesize a
     * literal for a runtime-generated custom scalar name, and would throw. [BanFieldNames] excludes
     * "_" (Kotlin reserves it as a declaration name) and "of" (the Kotlin GRT codegen's `_Arguments`
     * class always declares a nested `object of`, which a field literally named "of" collides with).
     */
    private val extensiveSchemaFragmentConfig: Config = Config.default +
        (SchemaSize to 150) +
        (BanFieldNames to setOf("_", "of")) +
        (
            // Types not listed here fall back to the default weight of 1.0.
            TypeTypeWeights to mapOf(
                TypeType.Object to 4.0,
                TypeType.Interface to 1.5,
                TypeType.Input to 1.5
            )
        ) +
        (GenInterfaceStubsIfNeeded to true) +
        (ObjectImplementsInterface to CompoundingWeight(.6, 4)) +
        (InterfaceImplementsInterface to CompoundingWeight(.4, 3)) +
        (ObjectTypeSize to 4..10) +
        (InterfaceTypeSize to 3..8) +
        (InputObjectTypeSize to 3..8) +
        (UnionTypeSize to 3..8) +
        (EnumTypeSize to 3..8) +
        (FieldArgumentWeight to CompoundingWeight(.5, 3)) +
        (DefaultValueWeight to 0.0) +
        (AppliedDirectiveWeight to CompoundingWeight(.4, 3)) +
        (DirectiveHasArgs to CompoundingWeight.Never) +
        (OneOfTypeWeight to 0.0) +
        (DescriptionLength to 0..0) +
        (IncludeBuiltinDirectives to false)

    override fun run() {
        val usedSeed = seed ?: Random.nextLong()
        val rs = RandomSource.seeded(usedSeed)
        val sdl = generateSDL(extensiveSchemaFragmentConfig, rs)

        // Fail loudly here, with the seed available, rather than as a confusing downstream error.
        SchemaParser().parse(sdl)

        output.parentFile?.mkdirs()
        output.writeText(
            "# AUTO-GENERATED by viaduct.arbitrary.cli.GenerateSchema -- do not edit.\n" +
                "# seed=$usedSeed\n" +
                "# Rerun with --seed=$usedSeed to reproduce this exact schema.\n\n" +
                sdl
        )

        echo("[GenerateSchema] wrote $output (seed=$usedSeed)")
    }

    /** No root types -- safe to concatenate with a schema that defines its own Query/Mutation/Subscription. */
    private fun generateSDL(
        cfg: Config,
        rs: RandomSource
    ): String {
        val types = Arb.graphQLTypes(cfg).next(rs)
        val printer = SchemaPrinter()

        return buildString {
            types.directives.values.forEach { appendLine(printer.print(it)) }
            types.enums.values.forEach { appendLine(printer.print(it)) }
            types.scalars.values.filterNot { it.name in builtinScalarNames }.forEach { appendLine(printer.print(it)) }
            types.interfaces.values.forEach { appendLine(printer.print(it)) }
            types.objects.values.forEach { appendLine(printer.print(it)) }
            types.unions.values.forEach { appendLine(printer.print(it)) }
            types.inputs.values.forEach { appendLine(printer.print(it)) }
        }
    }
}
