name: Deployment to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]
    paths: [ 'docs/**' ]

permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
defaults:
  run:
    shell: bash

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-22.04
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    env:
      DART_SASS_VERSION: 1.92.1
      GO_VERSION: 1.25.1
      HUGO_VERSION: 0.147.6
      NODE_VERSION: 22.18.0
      JAVA_VERSION: 17
      TZ: UTC
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod

      - name: Create directory for user-specific executable files
        run: |
          mkdir -p "${HOME}/.local"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        with:
          gradle-version: '8.14.3' # Quotes required to prevent YAML converting to number
        uses: gradle/actions/setup-gradle@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Dart Sass
        run: |
          curl -sLJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          tar -C "${HOME}/.local" -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          rm "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz"
          echo "${HOME}/.local/dart-sass" >> "${GITHUB_PATH}"

      - name: Verify installations
        run: |
          echo "Dart Sass: $(sass --version)"
          echo "Go: $(go version)"
          echo "Hugo: $(hugo version)"
          echo "Node.js: $(node --version)"
          echo "npm: $(npm --version)"
          echo "Java: $(java -version)"
          echo "Gradle: $(gradle --version)"

      - name: Install Node.js dependencies
        working-directory: ./docs
        run: |
          [[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true

      - name: Install postcss
        working-directory: ./docs
        run: npm install -D autoprefixer postcss postcss-cli

      - name: Configure Git
        run: |
          git config core.quotepath false

      - name: Cache restore
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/hugo_cache
          key: hugo-${{ github.run_id }}
          restore-keys:
            hugo-

      - name: Build hugo site
        working-directory: ./docs
        run: hugo build \
          --baseURL https://airbnb.io/viaduct \
          --cacheDir "${{ runner.temp }}/hugo_cache" \
          --gc \
          --minify \
          --cleanDestinationDir

      - name: Generate tenant kdocs
        run: ./gradlew :core:tenant:tenant-api:dokkaGenerate :core:service:dokkaGenerate

      - name: Cache save
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: ${{ runner.temp }}/hugo_cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/public
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
