name: Publish Demo Apps

on:
  workflow_dispatch:

jobs:
  # Validation job - checks versions and builds
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demoapp: [starwars, cli-starter, ktor-starter]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/libs.versions.toml', '**/build.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Validate ${{ matrix.demoapp }}
        run: |
          python3 ./.github/scripts/validate_demoapp.py ${{ matrix.demoapp }}

  # Publish job - runs copybara for each demo app
  publish:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demoapp:
          - name: starwars
            repo: viaduct-graphql/starwars
          - name: cli-starter
            repo: viaduct-graphql/cli-starter
          - name: ktor-starter
            repo: viaduct-graphql/ktor-starter
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: false

      - name: Run Copybara for ${{ matrix.demoapp.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.VIADUCT_GRAPHQL_GITHUB_ACCESS_TOKEN }}
        run: |
          # Configure git credentials
          git config --global credential.helper store
          echo "https://x-access-token:${GITHUB_TOKEN}@github.com" > ~/.git-credentials
          git config --global user.email "viabot@ductworks.io"
          git config --global user.name "ViaBot"

          # Debug: Check if config file exists
          ls -la ${{ github.workspace }}/.github/copybara/copy.bara.sky

          # Debug: Check what's inside the container
          docker run --rm -v ${{ github.workspace }}:/usr/src/app -w /usr/src/app olivr/copybara:latest ls -la /usr/src/app/.github/copybara/

          # Run copybara with explicit last-rev to limit commit range
          docker run --rm \
            -v ${{ github.workspace }}:/usr/src/app \
            -v ~/.git-credentials:/root/.git-credentials \
            -v ~/.gitconfig:/root/.gitconfig \
            -w /usr/src/app \
            olivr/copybara:latest \
            copybara \
            .github/copybara/copy.bara.sky \
            airbnb-viaduct-to-${{ matrix.demoapp.name }} \
            --git-destination-url=https://github.com/${{ matrix.demoapp.repo }}.git \
            --git-committer-email=viabot@ductworks.io \
            --git-committer-name=ViaBot \
            --last-rev=c7791a39a9f09cc9eea299ddbd670059c034ec75 \
            --force \
            -v SOURCE_REPO=file:///usr/src/app \
            -v SOURCE_REF=${{ github.sha }} \
            -v DEMOAPP_NAME=${{ matrix.demoapp.name }} \
            -v DESTINATION_REPO=https://github.com/${{ matrix.demoapp.repo }}.git
