name: Publish Demo Apps

on:
  workflow_dispatch:

jobs:
  # Validation job - checks versions and builds
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demoapp: [starwars, cli-starter, ktor-starter]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/libs.versions.toml', '**/build.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Validate ${{ matrix.demoapp }}
        run: |
          python3 ./.github/scripts/validate_demoapp.py ${{ matrix.demoapp }}

  # Publish job - runs copybara for each demo app
  publish:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demoapp:
          - name: starwars
            repo: viaduct-graphql/starwars
          - name: cli-starter
            repo: viaduct-graphql/cli-starter
          - name: ktor-starter
            repo: viaduct-graphql/ktor-starter
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: false

      - name: Run Copybara for ${{ matrix.demoapp.name }}
        uses: olivr/copybara-action@v1.2.3
        with:
          ssh_key: ${{ secrets.VIADUCT_GRAPHQL_GITHUB_ACCESS_TOKEN }}
          access_token: ${{ secrets.VIADUCT_GRAPHQL_GITHUB_ACCESS_TOKEN }}
          sot_repo: airbnb/viaduct
          sot_branch: ${{ github.ref_name }}
          destination_repo: ${{ matrix.demoapp.repo }}
          destination_branch: main
          custom_config: .github/copybara/copy.bara.sky
          workflow: airbnb-viaduct-to-${{ matrix.demoapp.name }}
          committer: ViaBot <viabot@ductworks.io>
          copybara_options: --force --last-rev=c7791a39a9f09cc9eea299ddbd670059c034ec75 -v SOURCE_REF=${{ github.sha }} -v DEMOAPP_NAME=${{ matrix.demoapp.name }}
