name: Publish Demo Apps

on:
  workflow_dispatch:

jobs:
  # Validation job - checks versions and builds
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demoapp: [starwars, cli-starter, ktor-starter]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/libs.versions.toml', '**/build.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Validate ${{ matrix.demoapp }}
        run: |
          python3 ./.github/scripts/validate_demoapp.py ${{ matrix.demoapp }}

  # Publish job - runs copybara for each demo app
  publish:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demoapp:
          - name: starwars
            repo: viaduct-graphql/starwars
          - name: cli-starter
            repo: viaduct-graphql/cli-starter
          - name: ktor-starter
            repo: viaduct-graphql/ktor-starter
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: false

      - name: Remove other branch refs to prevent copybara confusion
        run: |
          # Keep only the current branch, remove all other remote refs
          current_branch="${{ github.ref_name }}"
          cd ${{ github.workspace }}
          git for-each-ref --format='%(refname)' refs/remotes/origin | grep -v "refs/remotes/origin/$current_branch$" | xargs -r git update-ref -d

      - name: Run Copybara for ${{ matrix.demoapp.name }}
        uses: fireboy1919/copybara-action@v1.2.8
        with:
          access_token: ${{ secrets.VIADUCT_GRAPHQL_GITHUB_ACCESS_TOKEN }}
          sot_repo: airbnb/viaduct
          destination_repo: ${{ matrix.demoapp.repo }}
          workflow: airbnb-viaduct-to-${{ matrix.demoapp.name }}
          custom_config: .github/copybara/copy.bara.sky
          copybara_options: --git-destination-url=https://github.com/${{ matrix.demoapp.repo }}.git --git-committer-email=viabot@ductworks.io --git-committer-name=ViaBot --force -v SOURCE_REPO=file://${{ github.workspace }} -v SOURCE_REF=${{ github.sha }} -v DEMOAPP_NAME=${{ matrix.demoapp.name }} -v DESTINATION_REPO=https://github.com/${{ matrix.demoapp.repo }}.git
