name: Publish Demo Apps

on:
  workflow_dispatch:

jobs:
  # Validation job - checks versions and builds
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demoapp: [starwars, cli-starter, ktor-starter]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/gradle-wrapper.properties', '**/libs.versions.toml', '**/build.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Validate ${{ matrix.demoapp }}
        run: |
          python3 ./.github/scripts/validate_demoapp.py ${{ matrix.demoapp }}

  # Publish job - runs copybara for each demo app
  publish:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        demoapp:
          - name: starwars
            repo: viaduct-graphql/starwars
          - name: cli-starter
            repo: viaduct-graphql/cli-starter
          - name: ktor-starter
            repo: viaduct-graphql/ktor-starter
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Git credentials
        run: |
          git config --global credential.helper store
          echo "https://viabot:${{ secrets.VIADUCT_GRAPHQL_GITHUB_ACCESS_TOKEN }}@github.com" > ~/.git-credentials
          git config --global user.name "ViaBot"
          git config --global user.email "viabot@ductworks.io"

      - name: Pull Copybara Docker image
        run: docker pull olivr/copybara:latest

      - name: Run Copybara for ${{ matrix.demoapp.name }}
        run: |
          docker run \
            -v "${{ github.workspace }}:/workspace" \
            -v "$HOME/.gitconfig:/root/.gitconfig" \
            -v "$HOME/.git-credentials:/root/.git-credentials" \
            olivr/copybara:latest \
            copybara \
            /workspace/.github/copybara/copy.bara.sky \
            airbnb-viaduct-to-${{ matrix.demoapp.name }} \
            --force \
            --ignore-noop \
            --git-destination-url=https://github.com/${{ matrix.demoapp.repo }}.git \
            --git-committer-name=ViaBot \
            --git-committer-email=viabot@ductworks.io \
            -v \
            -v SOURCE_REPO=file:///workspace \
            -v DEMOAPP_NAME=${{ matrix.demoapp.name }} \
            -v DESTINATION_REPO=https://github.com/${{ matrix.demoapp.repo }}.git
